'''
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the 
even-valued terms.
'''
f0 = 0
f1 = 1
sum = 0
f_next = 0

while f_next < 4000000:
    f_next = f1 + f0
    if f_next % 2 == 0:
        sum += f_next
    f0 = f1
    f1 = f_next
    
print(sum)
